"""Drop unique

Revision ID: 9bc44f4343db
Revises: d7747549933f
Create Date: 2025-04-15 01:17:26.958222

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9bc44f4343db"
down_revision: Union[str, None] = "d7747549933f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("model_name_key", "model", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("model_name_key", "model", ["name"])
    # ### end Alembic commands ###
