"""Create model table

Revision ID: 27f25b1d508d
Revises: 88a00170c43b
Create Date: 2025-04-16 14:32:36.568685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f25b1d508d'
down_revision: Union[str, None] = '88a00170c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer_uuid', sa.Uuid(), nullable=False),
    sa.Column('category_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_uuid'], ['category.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_uuid'], ['manufacturer.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_model_uuid'), 'model', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_uuid'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
