"""Create part table

Revision ID: 8a946fe3087e
Revises: 27f25b1d508d
Create Date: 2025-04-16 14:33:05.087252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a946fe3087e'
down_revision: Union[str, None] = '27f25b1d508d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_uuid'], ['model.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name', 'model_uuid', name='unique_name_and_model_uuid')
    )
    op.create_index(op.f('ix_part_uuid'), 'part', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_uuid'), table_name='part')
    op.drop_table('part')
    # ### end Alembic commands ###
